# --- Rotary Encoder ---
# Enable the encoder
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
CONFIG_ZMK_STUDIO=y
# --- Power Management (Crucial for Wireless) ---
# Enable deep sleep state
CONFIG_ZMK_SLEEP=n
# Time in milliseconds before entering deep sleep (15 minutes)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# --- LED Underglow Config ---
# Enable RGB underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=2

# CONFIG_ZMK_RGB_UNDERGLOW_HUE_STEP=2
# CONFIG_ZMK_RGB_UNDERGLOW_SAT_STEP=5
# CONFIG_ZMK_RGB_UNDERGLOW_BRT_STEP=5

CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=80
# Set the driver to WS2812/SK6803 protocol
CONFIG_WS2812_STRIP=y

# Turn off LEDs automatically when the keyboard goes idle
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=n
CONFIG_ZMK_IDLE_TIMEOUT=600000

# --- External Power Routing ---
# Enable the external power cutoff switch
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y

# --- Enable Mouse For Horozontal Scroll ---
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_SETTINGS_RESET_ON_START=y